package com.pfe.notification.domain.model;

public enum NotificationType {
    POLICY_CREATED,
    POLICY_APPROVED,
    POLICY_RENEWED,
    POLICY_EXPIRING,
    POLICY_CANCELLED,
    INVOICE_GENERATED,
    INVOICE_OVERDUE,
    PAYMENT_REMINDER,
    CLAIM_SUBMITTED,
    CLAIM_APPROVED,
    CLAIM_UNDER_REVIEW,
    CLAIM_PAID,
    CLAIM_REJECTED,
    PAYMENT_RECEIVED
}
