package com.pfe.workflow.domain.model;

public enum AuditAction {
    // Client actions
    CLIENT_CREATED,
    CLIENT_UPDATED,
    CLIENT_DELETED,
    CLIENT_ACTIVATED,
    CLIENT_DEACTIVATED,
    
    // Policy actions
    POLICY_CREATED,
    POLICY_UPDATED,
    POLICY_SUBMITTED,
    POLICY_APPROVED,
    POLICY_REJECTED,
    POLICY_CANCELLED,
    POLICY_EXPIRED,
    POLICY_RENEWED,
    
    // Claim actions
    CLAIM_CREATED,
    CLAIM_UPDATED,
    CLAIM_SUBMITTED,
    CLAIM_REVIEWED,
    CLAIM_APPROVED,
    CLAIM_REJECTED,
    CLAIM_INFO_REQUESTED,
    CLAIM_PAYOUT_INITIATED,
    CLAIM_MARKED_AS_PAID,
    CLAIM_CLOSED,
    CLAIM_DELETED,
    
    // Billing actions
    INVOICE_CREATED,
    INVOICE_PAID,
    INVOICE_CANCELLED,
    INVOICE_OVERDUE,
    PAYMENT_CREATED,
    PAYMENT_PROCESSED,
    
    // User actions
    USER_LOGIN,
    USER_LOGOUT,
    USER_REGISTERED,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    
    // System actions
    SLA_VIOLATED,
    ESCALATION_CREATED,
    ESCALATION_RESOLVED,
    SAGA_STARTED,
    SAGA_COMPLETED,
    SAGA_FAILED,
    SAGA_COMPENSATED
}
